#ifndef QCAMERAINTERFACE_GLOBAL_H
#define QCAMERAINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>
//#include <QtGui>

#ifdef QCAMERAINTERFACE_LIB
# define QCAMERAINTERFACE_EXPORT Q_DECL_EXPORT
#else
# define QCAMERAINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // QCAMERAINTERFACE_GLOBAL_H
